version: "3.9"
services:
  signalR:
    image: signalr-chat
    environment:
      - REDIS=0.0.0.0:6379
    depends_on:
      - "redis"
    build: ./signalR
    links:
      - "redis"
    ports:
      - "5000:80"
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
